### ISSUE TITLE
not getting status from hub

### ISSUE THREAD

**Issue by mrobertson1992** [szokeptr/homebridge-tradfri-plugin#11]
it works about 90% of the time for me with the exception of the grouping error previously mentioned. my main issue is that homebridge is not displaying the live status of the lights .e.g if I turn on the lights using a switch or the Ikea app this is not reflected in the home app and I have to manually sync them

**Comment by szokeptr** [comment]
Can you confirm you are using the latest version of the plugin?

**Comment by mrobertson1992** [comment]
just double checked and I'm on 1.1.0

**Comment by mrobertson1992** [comment]
just done a hard reset of the Tradfri hub and re-added homebridge and this has resolved the error so think this was an issue with the hub rather than the plugin
