### ISSUE TITLE
hub reboot loop

### ISSUE THREAD

**Issue by mrobertson1992** [szokeptr/homebridge-tradfri-plugin#12]
sorry just notice another issue, when homebridge is running on the network every 60-90 seconds the tradfri hub looses connection to the network then restarts. when homebridge is turned off it functions normally

**Comment by szokeptr** [comment]
How many bulbs do you have? I suspect that the persistent connections may be the problem, for each bulb the plugin opens a connection and gets any change to the bulb state and the gateway might not like it.

**Comment by mrobertson1992** [comment]
currently have 3 gu10's connected to a single fitting and a controller connected to the hub. I will leave this until tomorrow and see if the hard reset has resolved this as it has not restarted since doing the reset. happy for you to close this in the meantime.

**Comment by mrobertson1992** [comment]
just reporting back that since the hard reset I have had no issues today, as I think this was a hub issue
