### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by tonijj** [szokeptr/homebridge-tradfri-plugin#15]
Hi, 

Pasted in the error below, have tried to update npm/nodejs etc

sudo npm install -g homebridge-tradfri-plugin
WARN engine homebridge-tradfri-plugin@1.1.0: wanted: {"node":">=7.7.2","homebridge":">=0.2.0"} (current: {"node":"4.3.2","npm":"2.14.12"})
homebridge-tradfri-plugin@1.1.0 /usr/local/lib/node_modules/homebridge-tradfri-plugin
└── command-exists@1.2.2

**Comment by szokeptr** [comment]
Your node version is old. Update to latest and install again.
