### ISSUE TITLE
Float LED Panel, no color temperature

### ISSUE THREAD

**Issue by tillsteinbach** [szokeptr/homebridge-tradfri-plugin#16]
I have a Float LED panel: http://www.ikea.com/de/de/catalog/products/10302969/
Dimming works through homebridge, but I have no controls for the color temperature.

Can somebody help?

**Comment by szokeptr** [comment]
Can you post some more info, perhaps some data from the panels. I don’t have a door panel so can’t test.

**Comment by tillsteinbach** [comment]
Sure, what kind of information would you require?

**Comment by szokeptr** [comment]
Hi, sorry for the delay, if this is still a problem please show the output of a simple GET request to the bulb endpoint with coap-client.
