### ISSUE TITLE
coap client time out

### ISSUE THREAD

**Issue by mrobertson1992** [szokeptr/homebridge-tradfri-plugin#17]
so after todays hub update I now get this error 
Command timed out: coap-client -u 'Client_identity' -k 'kU8kRxerdwEnQ0PC' -B 5 coaps://10.0.1.48:5684/15001

**Comment by szokeptr** [comment]
Is the IP address of the gateway fixed?

**Comment by mrobertson1992** [comment]
yeah sorted today, it was an issue at my providers end updating the router
