### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by matthijsotterloo** [szokeptr/homebridge-tradfri-plugin#19]
Hi!

I'm sure the IP of the gateway and the 'Security code' are correct.
But for some reason when starting homebridge I keep getting this error:

 /bin/sh: 1: coap-client: not found
 coap-client -u 'Client_identity' -k '2kZBpYULSBOojrxc' -B 5 coaps://192.168.178.95:5684/15001
[8/20/2017, 7:42:27 PM] [Tradfri] Cannot get devices from gateway! Is the Host and Key correct in config.json?

What's wrong?

**Comment by ghost** [comment]
run these command in this order


sudo apt-get install autoconf libtool automake
git clone --recursive https://github.com/obgm/libcoap.git
cd libcoap
git checkout dtls
git submodule update --init --recursive
./autogen.sh
./configure --disable-documentation --disable-shared
make
sudo make install


after that you can run homebridge if you added the platform

**Comment by boywithaxe** [comment]
Still comes back with the same error, but having said that I'm running this on High Sierra, and I wonder if that is the issue. I'll give it a go on my Sierra machine or set up a basic ubuntu server

**Comment by ghost** [comment]
Yeah that could be the reason. The command resplve the issue on a raspi
Am 10.09.2017 um 09:44 schrieb Greg Szydlo <notifications@github.com<mailto:notifications@github.com>>:


Still comes back with the same error, but having said that I'm running this on High Sierra, and I wonder if that is the issue. I'll give it a go on my Sierra machine or set up a basic ubuntu server

**Comment by szokeptr** [comment]
Hello! Ikea pushed a firmware update to the gateway which changed around some stuff with DTLS authentication. I implemented the new auth flow, please update your gateway and this plugin to latest version.
