### ISSUE TITLE
Getting: "WARN received alert, peer has been invalidated"

### ISSUE THREAD

**Issue by DavidNolander** [szokeptr/homebridge-tradfri-plugin#21]
Hi

All seems ok but i get:
Sep 12 01:07:05 WARN received alert, peer has been invalidated
Sep 12 01:07:05 ALRT 20 invalidate peer
coap-client -u 'Client_identity' -k 'KKI8RcgcEE0h1FBi' -B 5 coaps://192.168.1.8:5684/15001
[Tradfri] Command timed out: coap-client -u 'Client_identity' -k 'KKI8RcgcEE0h1FBi' -B 5 coaps://192.168.1.8:5684/15001

Any clue whats wrong?

**Comment by SubZane** [comment]
+1 Same error for me

**Comment by SubZane** [comment]
It seems to be the error message that you get when the gateway key is invalid.

I re-entered the key and now it works! Must have been a typo.
