### ISSUE TITLE
Does the plugin expose the Tradfri Dimmer as an HomeKit accessory?

### ISSUE THREAD

**Issue by brotkasten87** [szokeptr/homebridge-tradfri-plugin#23]
Hello,

I wonder if it's possible to expose the Tradfri Dimmer dial as an HomeKit dimmer accessory?
That would be awesome because it would allow to use the dimmer for various functions like brightness, volume (of connected speakers) and so on.

Thanks in advance!

**Comment by szokeptr** [comment]
Hello! No, unfortunately you can't use the remote controls as an accessory.
