### ISSUE TITLE
Boot loop of trådfri gateway with plugin

### ISSUE THREAD

**Issue by loftux** [szokeptr/homebridge-tradfri-plugin#24]
When first starting homebridge with this plugin, all runs smoothly for a period of time.
But after a while, the Trådfri Gateway (on firmware 1.1.0015) is starting to reboot constantly.
Shutting of homebridge, and the gateway starts working again.
I'm running on RaspberryPi (Jessie), just installed a week ago so I assume all components are the latest in terms of homebridge and plugins.

As vague as this error description is, I'm more curious if one can actually get it to work, or if this is a known issue. I guess we are all waiting for homekit support in the gateway, and it may be close to release (no one but IKEA knows), but until then it would be great to have this working.

**Comment by stoprocent** [comment]
I've experienced exactly same thing. 
I would suspect IKEA's gateway as even their app had problems managing light bulbs. 

Is it possible it's connected to a number of opened connections? I have about 25 IKEA devices (remotes and bulbs) and homebridge plugin is keeping all of them alive. 

Maybe gateway is to shit to handle this.

**Comment by loftux** [comment]
I have only 1 remote and 7 bulbs so far. If it is that the gateway just can't handle that many requests it is a bit worrying if the hardware is going to cope with built-in HomeKit support. Maybe that is why it is taking so long for IKEA to release the update.

**Comment by szokeptr** [comment]
I also experience instability with the gateway, probably I will revert back to the old polling mechanism instead of the subscribe child process, maybe it’s more stable with that. What do you think?

**Comment by stoprocent** [comment]
I will try to proxy IKEA's App and see if they keep connections alive.

**Comment by duenorh** [comment]
I've got the same problem. Anyone got a fix?

**Comment by NexusFlight** [comment]
I’m also getting this issue, I’ve found that if I use my Ikea remote it allows the gateway to reset correctly and things work for a period of time.

**Comment by grischard** [comment]
Those of you who experience gateway crashes, what's your power supply? Using Ikea's supplied 2A USB power adapter instead of the USB port at the back of my router has solved the issue for me.

To keep the chatter down, instead of posting "me too" comments, you can hit 'Subscribe' at the top right of the page.

**Comment by NexusFlight** [comment]
I am using their supplied power adapter and cable, and their Ethernet cable.

**Comment by ericvoshall** [comment]
I have the same issue. it happens when I have the gateway plugged into the USB port on my router or if I use the included wall adapter.

**Comment by n3rd** [comment]
I'm experiencing the same problem, using the included power adapter and firmware version 1.2.42. I'm only using a single (color) light bulb so the number of devices can't be the problem. Any solutions yet?

**Comment by szokeptr** [comment]
Hi I updated today the plugin to version 1.1.1 which includes a new command queueing system and support for the new DTLS sessions. This should solve many stability issues. You must have the latest firmware on your gateway.
My gateway was also in bootloop with the old version of the plugin on a raspberry, but the new one seems to work just fine.
