### ISSUE TITLE
Lights not turning back on.

### ISSUE THREAD

**Issue by jamesgwhite** [szokeptr/homebridge-tradfri-plugin#26]
Hey, 

I'm still fairly new to all this. But I believe I've installed fine. I can see all my lights in the home app. I can turn the lights off but when I go to turn back on the appear to work but once I let go of the button they go off. They then become out of sync with the iKEA app. Any help would be great. 

Thanks in advance.

**Comment by szokeptr** [comment]
Hi I updated today the plugin to version 1.1.1 which includes a new command queueing system and support for the new DTLS sessions. This should solve many stability issues. You must have the latest firmware on your gateway.
