### ISSUE TITLE
After Gateway Update 1.2.42 no Blobs apear in Homebridge

### ISSUE THREAD

**Issue by Partyboy97** [szokeptr/homebridge-tradfri-plugin#27]
Hi,

my gateway automaticly update the firmware to 1.2.42. After that no blobs apear in the homebridge. 

But the Gateway apear after the Update in the Home App as Tradfri Gateway. You can add it as other HomeKit devices. If you have the 8 digit code of can scan the barcode. For me there is no code under my gateway and the Home App can’t scan the barcode. Hopfully Ikea Update the App asap and provide the HomeKit code over it.

**Comment by szokeptr** [comment]
Hello. You mean you got an update with integrated HomeKit support?

**Comment by Partyboy97** [comment]
Yes
![73917c71-cd53-42f3-9703-2c249c598d30](https://user-images.githubusercontent.com/30287831/32264092-4b11521c-bedd-11e7-85ba-e68dff9f0f33.png)

**Comment by boeserwolf** [comment]
Same here. Found this statement from IKEA:

> We at IKEA would like to inform you about a change to our TRÅDFRI Gateway. We are very happy to see your interest in our gateway and have seen that you are using the CoAP interface. We consider the CoAP interface as our internal interface not developed for third party usage and therefore we do not offer any technical support for this usage. However that does not mean that we want to hinder your work in any way.
> 
> There are some security improvements in a soon coming update that we would like to inform you about since it will break your implementation. **Technically the improvement is that the TRÅDFRI Gateway will start using DTLS Identities which you will need to handle in your application.**
> 
> Please use the Following string to connect to the TRÅDFRI Gateway and create a new DTLS Identity.
> 
> coap-client -m post -u "Client_identity" -k "SECURITY_CODE" -e '{"9090":"IDENTITY"}' "coaps://IP_ADDRESS:5684/15011/9063"
> 
> SECURITY_CODE is what is labelled on the Gateway label, IDENTITY is any string that is representing the connection.
> You will then get back a PRE_SHARED_KEY that can be use in all traffic after that.
> 
> coap-client -m get -u "IDENTITY" -k "PRE_SHARED_KEY" "coaps://IP_ADDRESS:5684/15001"
> 
> We also would like to request that the SECURITY_CODE that is printed on the gateway is never stored permanently in your application.
> 
> Best regards
> IKEA of Sweden Trådfri team

**Comment by Partyboy97** [comment]
App is out. Officle Homekit Support, but Szokeptr implemntation was better. As example the 3 default options for colorcan't be adjusted gradually.

**Comment by szokeptr** [comment]
Yes, a technician from Ikea reached out in email to let me know of the upcoming changes. I will update the plugin with that and some further improvements for stabilty in the weekend.

**Comment by szokeptr** [comment]
Hi guys! I updated today the plugin to version 1.1.1 which includes a new command queueing system and support for the new DTLS sessions. You must have the latest firmware on your gateway.
