### ISSUE TITLE
Support for Tradfri Plug/Outlet?

### ISSUE THREAD

**Issue by TangoTaker** [szokeptr/homebridge-tradfri-plugin#29]

**Comment by TangoTaker** [comment]
Does this plugin support the Tradfri Plug?

**Comment by nielsth** [comment]
Not at the moment I think. Would love to see support for the control outlet too, as it will likely still take IKEA a couple of months to implement it.

**Comment by szokeptr** [comment]
The outlets are not yet available in my country, Ikea’s site expects it in 2 weeks. Once I get my hand on one of these I can add support.

**Comment by nielsth** [comment]
That'd be great!

**Comment by dariusrosendahl** [comment]
👍  also looking for a plugin that can connect the Tradfri Plugs to homekit

**Comment by szokeptr** [comment]
I got a few of these today, I started working on an update for the plugin.

**Comment by szokeptr** [comment]
Outlet support is ready, package is now at 1.1.4.

**Comment by TangoTaker** [comment]
Working great so far, thanks
