### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by sandyjmacdonald** [szokeptr/homebridge-tradfri-plugin#3]
Install goes without hitch. However, when I fire up homebridge, nothing appears in my Home app on my iPhone. The standard output from homebridge says that the plugin has been initialised, but there's no further output from it. It also appears that the PSK is "undefined" in the call to coap-client despite it being correct.

I'm using Raspbian Lite on a Pi Zero W. If I uninstall the plugin and reinstall the homebridge-tradfri plugin then everything works as expected again.

**Comment by szokeptr** [comment]
In your config.json you must define the PSK named `key` and not `psk`. Probably it's a good idea to change that to `key`. I believe this is your problem, let me know if that's not the case!

**Comment by sandyjmacdonald** [comment]
I'll give that a try. Thanks!

**Comment by sandyjmacdonald** [comment]
Still not working. This time I get the following:

```
● homebridge.service - Node.js HomeKit Server
   Loaded: loaded (/etc/systemd/system/homebridge.service; enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2017-04-17 20:42:06 UTC; 779ms ago
  Process: 1510 ExecStart=/usr/local/bin/homebridge $HOMEBRIDGE_OPTS (code=exited, status=1/FAILURE)
 Main PID: 1510 (code=exited, status=1/FAILURE)

Apr 17 20:42:06 zerow homebridge[1510]: at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
Apr 17 20:42:06 zerow homebridge[1510]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
Apr 17 20:42:06 zerow homebridge[1510]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 17 20:42:06 zerow homebridge[1510]: at Module._compile (module.js:434:26)
Apr 17 20:42:06 zerow homebridge[1510]: at Object.Module._extensions..js (module.js:452:10)
Apr 17 20:42:06 zerow homebridge[1510]: at Module.load (module.js:355:32)
Apr 17 20:42:06 zerow homebridge[1510]: at Function.Module._load (module.js:310:12)
Apr 17 20:42:06 zerow homebridge[1510]: at Function.Module.runMain (module.js:475:10)
Apr 17 20:42:06 zerow systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Apr 17 20:42:06 zerow systemd[1]: Unit homebridge.service entered failed state.
```

**Comment by szokeptr** [comment]
What version of Node and Homebridge are you running?

**Comment by sandyjmacdonald** [comment]
Just the standard one that's bundled with Raspbian, so 4.0.0, I guess.

**Comment by szokeptr** [comment]
Can you share some more info about your setup? What versions are you running and are there any other homebridge plugins installed? I can't tell what the problem is by that log fragment.

**Comment by szokeptr** [comment]
I suspect that your config.json is not valid, can you please double check?

**Comment by szokeptr** [comment]
I am closing this because of no response. Please, reopen if the problem persists.

**Comment by sandyjmacdonald** [comment]
Sorry for the slow response on this! I've now updated to node.js v7.9.0 and it looks like everything is firing up properly, but I don't see Homebridge as an accessory when I try to add it.

Here is my `config.json`:

```

{
    "bridge": {
        "name": "Homebridge-Test",
        "username": "CC:22:3D:E3:CE:32",
        "port": 51826,
        "pin": "031-45-155"
    },

    "description": "Homebridge-Test",

    "accessories": [
    ],

    "platforms": [
    {
        "platform": "IkeaTradfri",
        "name": "Tradfri-Test",
        "host": "192.168.0.xxx",
        "key": "xxx"
    }
]
}
```

And here is the standard output when I run homebridge:

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[4/26/2017, 12:37:00 PM] Loaded plugin: homebridge-tradfri-plugin
[4/26/2017, 12:37:00 PM] Registering platform 'homebridge-tradfri.IkeaTradfri'
[4/26/2017, 12:37:00 PM] ---
[4/26/2017, 12:37:00 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/26/2017, 12:37:00 PM] ---
[4/26/2017, 12:37:00 PM] Loading 1 platforms...
[4/26/2017, 12:37:00 PM] [Tradfri-Test] Initializing IkeaTradfri platform...
[4/26/2017, 12:37:00 PM] Loading 0 accessories...
[4/26/2017, 12:37:01 PM] [Tradfri-Test] Initializing platform accessory 'White spectrum bulb 1'...
[4/26/2017, 12:37:01 PM] [Tradfri-Test] Initializing platform accessory 'White spectrum bulb 2'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 031-45-155 │
    └────────────┘

[4/26/2017, 12:37:01 PM] Homebridge is running on port 51826.
```

**Comment by szokeptr** [comment]
Please check out the [Common Issues](https://github.com/nfarina/homebridge#common-issues) section of the `homebridge` plugin: [https://github.com/nfarina/homebridge#common-issues](https://github.com/nfarina/homebridge#common-issues). If the problem persists, please reopen the issue.

**Comment by sandyjmacdonald** [comment]
Great! Thanks! I got it working. Can confirm that the issue was the "stuck username" one since I'd be deleting both the `persist` and `accessories` directories every time. Changing the username to `CC:11:3D:E3:CE:32` did the trick!

P.S. Really great work on the plugin. I'll switch my home setup over to this tonight. :-)
