### ISSUE TITLE
Siri switching on doesn't work

### ISSUE THREAD

**Issue by RedPepper** [szokeptr/homebridge-tradfri-plugin#4]
there seems to be a difference when switching on / off lights with Siri and with pressing the button in the Home App (from my observings  the values sent are different its sending a bool instead of a int via coap)

**Comment by szokeptr** [comment]
Thanks for pointing that out! It seems that this problem is not always consistent. Siri sometimes sends a boolean, sometimes a number. I fixed that now, should be ok if you update.

**Comment by RedPepper** [comment]
works now thank you for the quick fix
