### ISSUE TITLE
Stuck on Initializing IkeaTadfri 

### ISSUE THREAD

**Issue by talkaboutdesign** [szokeptr/homebridge-tradfri-plugin#7]
[4/22/2017, 9:58:14 PM] [Tradfri] Initializing IkeaTradfri platform...

Than it closes after min or so. Doesn't actually start.

**Comment by szerglyiphone** [comment]
I have a same issue. The Key is okay, and IP address is ok too.

**Comment by szokeptr** [comment]
@talkaboutdesign please update node to 6.x or preferably 7.x, after that update the plugin to 1.0.6, I just pushed a fix for some issues related to this.

**Comment by Honason** [comment]
With Node 7.10 and plugin 1.0.6 I have the same issue:
```
[5/6/2017, 12:36:24 AM] [Tradfri] Initializing IkeaTradfri platform...
(node:33502) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token v in JSON at position 0
(node:33502) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

And the config.json file is a valid JSON

**Comment by szokeptr** [comment]
I updated the plugin with better error handling, please update it then try again.

**Comment by Honason** [comment]
It works now 👍 my mistake was just wrong PSK. Error handling helped to guess where is the issue.
