### ISSUE TITLE
Bugg with same UUID

### ISSUE THREAD

**Issue by frhogdevelop** [szokeptr/homebridge-tradfri-plugin#8]
I found a bug when i have two groups with a device i each group that has the same name they somehow get the same UUID. Like this, Two groups i Trådfri app, one kitchen and one bedroom in each group there is a device called window.
that setup did not work, i had to change the names so they were not the same.

**Comment by szokeptr** [comment]
Thanks for reporting this! I was only using one group so this bug never occurred to me. I fixed it by appending the device ID to the name, so you should be fine now. Update to 1.1.0
